version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: fsbo_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fsbo_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fsbo_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - fsbo_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: fsbo_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fsbo_network

  # pgAdmin (Database Management Tool)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: fsbo_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fsbo.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - fsbo_network

volumes:
  postgres_data:
  redis_data:

networks:
  fsbo_network:
    driver: bridge 